import pytest
import jax
import jax.numpy as jnp
from jax.config import config
config.update('jax_enable_x64', True) # Enable float64 for precision
import numpy as np # For healpy and test data

from jax_healpix.synthesis import MapSynthesizer
from jax_healpix.transform import HealpixTransformer # For analysis of output

# Test parameters
NSIDE_TEST = 2
LMAX_TEST = 2 * NSIDE_TEST # Adjusted LMAX based on common use (e.g. 2*nside or 3*nside-1)
RAND_SEED = 42

@pytest.fixture
def synthesizer():
    return MapSynthesizer()

@pytest.fixture
def transformer_for_analysis():
    return HealpixTransformer(nside=NSIDE_TEST, l_max=LMAX_TEST)

def test_map_synthesizer_creation(synthesizer):
    assert synthesizer.transformer is None

    transformer = HealpixTransformer(nside=NSIDE_TEST, l_max=LMAX_TEST)
    synthesizer_with_trans = MapSynthesizer(healpix_transformer=transformer)
    assert synthesizer_with_trans.transformer is transformer

def test_synfast_temperature_only(synthesizer, transformer_for_analysis):
    nside = NSIDE_TEST
    lmax = LMAX_TEST

    # For T-only, n_tracers_for_syn_alm = 1.
    # cls_input for _syn_alm expects [n_cl_combinations_flat, l_max+1].
    # For n_tracers=1, n_cl_combinations_flat = 1*(1+1)/2 = 1. This is Cl_TT.
    cl_tt = jnp.ones(lmax + 1, dtype=jnp.float64) * 1e-4
    cl_tt = cl_tt.at[0:2].set(0)  # Monopole, dipole usually zero

    # synfast's cls_dict argument is passed as cl_input_for_syn_alm
    # It infers n_tracers_for_syn_alm from cls_dict.shape[0] if using the formula
    # N = (-1 + sqrt(1 + 8*num_cl_flat))/2.
    # If cls_dict is (1, lmax+1), then num_cl_flat=1, N=1. This is correct for T-only.
    cls_input_for_synfast = cl_tt[None, :] # Shape (1, lmax+1)

    # tracer_info maps spin outputs to indices of raw alms from _syn_alm
    # If _syn_alm used n_tracers=1, its output is (1, L, M).
    # For T-map (spin 0), we take the 0-th tracer from raw_alms.
    tracer_info_t_only = {'T': {'cl_idx': 0}}

    maps_dict = synthesizer.synfast(
        nside=nside,
        l_max=lmax,
        spins_to_generate=(0,),
        tracer_info=tracer_info_t_only,
        cls_input=cls_input_for_synfast,
        rand_seed=RAND_SEED,
        healpix_transformer_instance=transformer_for_analysis
    )

    assert 0 in maps_dict
    map_T_2d = maps_dict[0]
    assert map_T_2d.shape == (4 * nside - 1, 4 * nside)

    alm_dict_out = transformer_for_analysis.map2alm(
        maps_dict={0: map_T_2d},
        spins_in_map=(0,)
    )
    alm_T_out = alm_dict_out[0]
    cl_tt_out = transformer_for_analysis.compute_cl(alm_T_out)

    assert cl_tt_out.shape == (lmax + 1,)
    assert not jnp.all(jnp.isclose(cl_tt_out[2:], 0.0))

    mean_power_in = jnp.mean(cl_tt[2:])
    mean_power_out = jnp.mean(cl_tt_out[2:])
    # Increased rtol because it's a statistical comparison of a single realization.
    assert jnp.isclose(mean_power_out, mean_power_in, rtol=1.5) # Allow up to 150% diff for single draw


def test_synfast_polarization_e_b_from_separate_cls(synthesizer, transformer_for_analysis):
    nside = NSIDE_TEST
    lmax = LMAX_TEST

    cl_ee = jnp.ones(lmax + 1, dtype=jnp.float64) * 5e-5
    cl_ee = cl_ee.at[0:2].set(0)
    cl_bb = jnp.ones(lmax + 1, dtype=jnp.float64) * 2e-5
    cl_bb = cl_bb.at[0:2].set(0)
    cl_eb_zeros = jnp.zeros(lmax+1, dtype=jnp.float64)

    # For _syn_alm with n_tracers=2 (for E and B streams):
    # cls_input should contain [Cl_EE, Cl_EB, Cl_BB] in its first dimension (flattened upper triangle).
    # So, shape will be (3, lmax+1).
    # Order: EE (idx 0 for E-E), EB (idx 0 for E-B cross), BB (idx 1 for B-B if E is 0, B is 1).
    # If tracers are (E,B):
    #   (0,0) -> EE
    #   (0,1) -> EB
    #   (1,1) -> BB
    cls_input_for_synfast_pol = jnp.stack([cl_ee, cl_eb_zeros, cl_bb]) # (3, lmax+1)

    # tracer_info maps how the output spins (E, B) correspond to the indices of the
    # n_tracers_for_syn_alm streams generated by _syn_alm.
    # If _syn_alm is called with n_tracers=2 (derived from 3 Cl components), it produces 2 alm streams.
    # tracer_info tells synfast:
    #  - E-alms (for map spin 2) should come from the 0-th stream of _syn_alm.
    #  - B-alms (for map spin -2) should come from the 1-st stream of _syn_alm.
    tracer_info_pol = {
        'E': {'cl_idx': 0}, # E alms are the 0-th tracer output from _syn_alm
        'B': {'cl_idx': 1}  # B alms are the 1-st tracer output from _syn_alm
    }

    maps_dict_pol = synthesizer.synfast(
        nside=nside,
        l_max=lmax,
        spins_to_generate=(2, -2), # We want Q and U maps, so need E and B alms
        tracer_info=tracer_info_pol,
        cls_input=cls_input_for_synfast_pol,
        rand_seed=RAND_SEED,
        healpix_transformer_instance=transformer_for_analysis
    )

    assert 2 in maps_dict_pol # Q map (from E alms)
    assert -2 in maps_dict_pol # U map (from B alms)
    map_Q_2d = maps_dict_pol[2]
    map_U_2d = maps_dict_pol[-2]

    assert map_Q_2d.shape == (4 * nside - 1, 4 * nside)
    assert map_U_2d.shape == (4 * nside - 1, 4 * nside)

    # Analyze output Cls
    alm_dict_out_pol = transformer_for_analysis.map2alm(
        maps_dict={2: map_Q_2d, -2: map_U_2d}, # map2alm expects Q at key 2, U at key -2
        spins_in_map=(2, -2)
    )
    alm_E_out = alm_dict_out_pol[2] # E-mode alms
    alm_B_out = alm_dict_out_pol[-2] # B-mode alms

    cl_ee_out = transformer_for_analysis.compute_cl(alm_E_out)
    cl_bb_out = transformer_for_analysis.compute_cl(alm_B_out)
    # Cross Cl_EB_out (optional, can also check if it's near zero)
    cl_eb_out_dict = transformer_for_analysis.compute_cl({0: alm_E_out, 1: alm_B_out}) # Use dummy keys for compute_cl
    cl_eb_out = cl_eb_out_dict[(0,1)]


    assert cl_ee_out.shape == (lmax + 1,)
    assert cl_bb_out.shape == (lmax + 1,)
    assert not jnp.all(jnp.isclose(cl_ee_out[2:], 0.0))
    assert not jnp.all(jnp.isclose(cl_bb_out[2:], 0.0))

    # Loose check on average power
    assert jnp.isclose(jnp.mean(cl_ee_out[2:]), jnp.mean(cl_ee[2:]), rtol=1.5)
    assert jnp.isclose(jnp.mean(cl_bb_out[2:]), jnp.mean(cl_bb[2:]), rtol=1.5)
    # Check if cross is small (as input EB was zero)
    assert jnp.mean(jnp.abs(cl_eb_out[2:])) < 1e-5 # Should be statistically consistent with zero
```
